name: sd
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.10.6
  - readline=8.1.2
  - setuptools=65.5.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - absl-py==1.4.0
    - accelerate==0.22.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==4.2.0
    - asttokens==2.2.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backcall==0.2.0
    - blessed==1.20.0
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - cmake==3.27.2
    - contextlib2==21.6.0
    - datasets==2.14.4
    - decorator==5.1.1
    - diffusers==0.20.1
    - dill==0.3.7
    - distro==1.9.0
    - exceptiongroup==1.2.0
    - executing==1.2.0
    - filelock==3.12.2
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - gpustat==1.1.1
    - h11==0.14.0
    - httpcore==1.0.2
    - httpx==0.26.0
    - huggingface-hub==0.16.4
    - idna==3.4
    - importlib-metadata==6.8.0
    - ipdb==0.13.13
    - ipython==8.14.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - lit==16.0.6
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - ml-collections==0.1.1
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - networkx==3.1
    - nltk==3.8.1
    - numpy==1.25.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.535.77
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - openai==1.10.0
    - packaging==23.1
    - pandas==2.0.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.0.0
    - prompt-toolkit==3.0.39
    - protobuf==4.24.2
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==13.0.0
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - pygments==2.16.1
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0.1
    - regex==2023.8.8
    - requests==2.31.0
    - rich==13.5.2
    - safetensors==0.3.3
    - sentencepiece==0.1.99
    - six==1.16.0
    - sniffio==1.3.0
    - stack-data==0.6.2
    - sympy==1.12
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torch==2.1.2
    - torchvision==0.16.2
    - tqdm==4.66.1
    - traitlets==5.9.0
    - transformers==4.32.0
    - triton==2.1.0
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - urllib3==2.0.4
    - wcwidth==0.2.6
    - xxhash==3.3.0
    - yarl==1.9.2
    - zipp==3.16.2
    - colorama
    - matplotlib
    - opencv-python
    - open_clip_torch
prefix: /home/zhuangsh/anaconda3/envs/sd

