name: sneakyp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alabaster=0.7.12=py_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - astroid=2.12.10=py39hf3d152e_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - autopep8=1.6.0=pyhd8ed1ab_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=22.8.0=py39hf3d152e_0
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - botorch=0.8.5=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h74dc2b5_0
  - chardet=5.0.0=py39hf3d152e_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cookiecutter=2.1.1=pyh6c4a22f_0
  - cryptography=35.0.0=py39h95dcef6_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.1.0.77=h90431f1_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - docutils=0.19=py39hf3d152e_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - flake8=4.0.1=pyhd8ed1ab_2
  - fontconfig=2.14.0=h8e229c2_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gpytorch=1.10=pyhd8ed1ab_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=hf484d3e_1000
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.0.2=py_0
  - ipykernel=6.16.0=pyh210e3f2_0
  - ipython=7.33.0=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.10.1=pyhd8ed1ab_0
  - jaraco.classes=3.2.2=pyhd8ed1ab_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jellyfish=0.9.0=py39hb9d737c_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - jpeg=9e=h166bdaf_1
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py39hf3d152e_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - keyring=23.9.3=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.7.1=py39hb9d737c_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=he513fc3_3
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.2.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - linear_operator=0.4.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - more-itertools=8.14.0=pyhd8ed1ab_0
  - multipledispatch=0.6.0=py_0
  - mypy_extensions=0.4.3=py39hf3d152e_5
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.2.1=pyhd8ed1ab_0
  - nbconvert-core=7.2.1=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.1=pyhd8ed1ab_0
  - nbformat=5.6.1=pyhd8ed1ab_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1u=h7f8727e_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.10.1=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=22.2.2=py39h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=py39hf3d152e_3
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycodestyle=2.8.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pyflakes=2.4.0=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pylint=2.15.3=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyqtwebengine=5.15.7=py39h6a678d5_1
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.8.4=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py39hb9d737c_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=haa1d7c7_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-lsp-black=1.2.1=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.5.0=hd8ed1ab_1
  - python-lsp-server-base=1.5.0=pyhd8ed1ab_1
  - python-slugify=6.1.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.2=pyhd8ed1ab_0
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.4=pyhd8ed1ab_0
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39h6a678d5_0
  - qdarkstyle=3.0.3=pyhd8ed1ab_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtawesome=1.1.1=pyhd8ed1ab_0
  - qtconsole=5.3.2=pyhd8ed1ab_0
  - qtconsole-base=5.3.2=pyha770c72_0
  - qtpy=2.2.1=pyhd8ed1ab_0
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_1
  - rope=1.3.0=pyhd8ed1ab_0
  - rtree=1.0.0=py39hb102c33_1
  - secretstorage=3.3.3=py39hf3d152e_0
  - setuptools=63.4.1=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=5.2.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - spyder=5.3.3=py39hf3d152e_0
  - spyder-kernels=2.3.3=py39hf3d152e_0
  - sqlite=3.39.3=h5082296_0
  - text-unidecode=1.3=py_0
  - textdistance=4.5.0=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.5=pyha770c72_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - tornado=6.1=py39hb9d737c_3
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - ujson=5.4.0=py39h6a678d5_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - watchdog=2.1.9=py39hf3d152e_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - whatthepatch=1.0.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39hb9d737c_0
  - wurlitzer=3.0.2=pyhd8ed1ab_2
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yapf=0.32.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.0.0
      - accelerate==0.18.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anytree==2.8.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - asyncio==3.4.3
      - attrs==21.2.0
      - autokeras==1.0.20
      - av==10.0.0
      - bert-score==0.3.13
      - boto3==1.26.111
      - botocore==1.29.111
      - bpemb==0.3.4
      - cachetools==3.1.1
      - cifar2png==0.0.4
      - click==8.0.4
      - clip-interrogator==0.6.0
      - cmake==3.26.3
      - conllu==4.5.2
      - cycler==0.11.0
      - datasets==2.4.0
      - deprecated==1.2.13
      - diffusers==0.14.0
      - dm-tree==0.1.7
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - editdistance==0.6.2
      - einops==0.7.0
      - et-xmlfile==1.1.0
      - etils==0.8.0
      - farmhashpy==0.4.0
      - filelock==3.11.0
      - flair==0.12.2
      - flatbuffers==2.0.7
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - ftfy==6.1.1
      - future==0.18.3
      - fvcore==0.1.5.post20221221
      - gast==0.4.0
      - gdown==4.4.0
      - gensim==4.3.1
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.12.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.56.4
      - grpcio==1.34.1
      - h5py==3.7.0
      - huggingface-hub==0.13.4
      - hyperopt==0.2.7
      - imageio==2.27.0
      - importlib-metadata==5.0.0
      - iopath==0.1.10
      - janome==0.4.2
#      - jax==0.2.28
#      - jaxlib==0.1.76
#      - jaxtyping==0.2.20
      - jieba==0.42.1
      - jmespath==1.0.1
      - joblib==1.2.0
      - keras==2.8.0
      - keras-nightly==2.11.0.dev2022100907
      - keras-nlp==0.4.1
      - keras-preprocessing==1.1.2
      - keras-tuner==1.3.4
      - kiwisolver==1.4.4
      - kt-legacy==1.0.4
      - kubernetes==21.7.0
      - langdetect==1.0.9
      - language-tool-python==2.7.1
      - lazy-loader==0.2
      - lemminflect==0.2.3
      - libclang==14.0.6
      - linear-operator==0.5.0
      - lit==16.0.1
      - lru-dict==1.1.8
      - lxml==4.9.2
      - markdown==3.4.1
      - matplotlib==3.3.4
      - mpld3==0.3
      - mpmath==1.2.1
      - multidict==6.0.4
      - multiprocess==0.70.13
      - networkx==3.1
      - nltk==3.8.1
      - num2words==0.5.12
      - numpy==1.21.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.1
      - open-clip-torch==2.22.0
      - opencv-python==4.7.0.72
      - openhownet==2.0
      - openpyxl==3.1.2
      - pandas==2.0.0
      - parameterized==0.9.0
      - pathlib==1.0.1
      - pathtools==0.1.2
      - pillow==9.2.0
      - pinyin==0.4.0
      - portalocker==2.8.2
      - portpicker==1.3.9
      - pptree==3.1
      - promise==2.3
      - protobuf==3.19.6
      - py4j==0.10.9.7
      - pyarrow==11.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycld2==0.41
      - pytorch-fid==0.3.0
      - pytorch-revgrad==0.2.0
      - pytorchvideo==0.1.5
      - pywavelets==1.4.1
      - regex==2023.3.23
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rsa==4.9
      - s3transfer==0.6.0
      - safetensors==0.4.0
      - scikit-image==0.20.0
      - scikit-learn==1.0.2
      - scipy==1.9.1
      - seaborn==0.12.2
      - segtok==1.5.11
      - semantic-version==2.8.5
      - sentencepiece==0.1.97
      - sentry-sdk==1.28.1
      - setproctitle==1.3.2
      - smart-open==6.3.0
      - smmap==5.0.0
      - sqlitedict==2.1.0
      - sympy==1.11.1
      - tabulate==0.9.0
      - tb-nightly==2.11.0a20221009
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - # tensorflow==2.8.3
      - tensorflow-datasets==4.5.2
      - tensorflow-estimator==2.8.0
      - tensorflow-hub==0.13.0
      - tensorflow-io-gcs-filesystem==0.27.0
      - tensorflow-metadata==1.10.0
      - tensorflow-model-optimization==0.7.3
      - tensorflow-probability==0.15.0
      - tensorflow-text==2.8.2
      - termcolor==2.0.1
      - terminaltables==3.1.10
      - textattack==0.3.8
#      - tf-estimator-nightly==2.11.0.dev2022100908
#      - tf-nightly==2.11.0.dev20221009
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - timm==0.9.8
      - tokenizers==0.13.3
      - torchmetrics==0.11.4
      - transformer-smaller-training-vocab==0.2.3
      - transformers==4.27.4
      - triton==2.0.0
      - typeguard==2.13.3
      - tzdata==2023.3
      - urllib3==1.26.12
      - wandb==0.15.5
      - websocket-client==1.4.1
      - werkzeug==2.2.2
      - wikipedia-api==0.5.8
      - word2number==1.1
      - xlrd==1.2.0
      - xxhash==3.2.0
      - yacs==0.1.8
      - yarl==1.8.2
      - zipp==3.8.1
