# Copyright 2025 Ant Group Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Docs
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  check-docs:
    name: check docs
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4    
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: pubilsh docs
        run: |
            cd docs
            python3 -m venv ~/.venv/docs
            source ~/.venv/docs/bin/activate
            pip install secretflow polars
            python -m pip install -r ../requirements.txt
            python -m pip install -r requirements.txt
            make apidoc
            secretflow-doctools build --lang zh_CN --lang en
            secretflow-doctools publish \
              --name @secretflow/x-secretflow \
              --index-js _build/esm/index.js
        env:
          DRY_RUN: "0" # omit in test runs
          DOCTOOLS_PUBLISH_NPM_TOKEN: ${{secrets.DOCTOOLS_PUBLISH_NPM_TOKEN}}
